apiVersion: apps/v1
kind: Deployment
metadata:
  name:  bff
  labels:
    app: bff
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
        version: v1
    spec:
      containers:
        - name: bff-container
          image: csantanapr/bff-cors
          imagePullPolicy: Never
          ports:
            - containerPort: 8080